//! Ambient `struct` owner strategy acceptance.
//!
//! `struct` is a builtin privileged AST meta function: called directly it
//! never creates a `MetaInstance(struct, arguments)` scope of its own.  The
//! generated type attaches to the ambient declaration environment, and at
//! one declaration level the same navigation name + top pattern may be
//! generated by `struct` exactly once — a second generation is a hard error
//! that points at the existing binding (the recorded binder never feeds
//! type identity; it is diagnostic material only).

mod support;

use lang_build::{
    extract_single_call_site, BuildManifest, CanonicalFullNavigation, CanonicalPatternAtom,
    CanonicalPatternBuilder, CanonicalPatternValue, CanonicalTypeObservation, CompilationWorld,
    InvocationOutcome, OrdinaryInvocationContext, OrdinaryInvocationFailure,
    PatternNavigationInput, PatternValueId, PolicyMode, Provenance, SemanticOwnerId,
    SemanticValuePayload, TypeValueId,
};
use support::{build_fixture_error, build_single_fixture_world, initializer_from_source};

fn invoke_struct(
    world: &mut CompilationWorld,
    spelling: &str,
    provenance: &str,
) -> Result<InvocationOutcome, OrdinaryInvocationFailure> {
    let initializer = initializer_from_source(spelling);
    let call_site = extract_single_call_site(&initializer).expect("normalized struct call");
    world.invoke_ordinary_call(
        world.package_root_node(),
        &call_site,
        OrdinaryInvocationContext::open_static(&[PolicyMode::Const]),
        Provenance::new(provenance),
    )
}

fn returned_struct_material(
    outcome: &InvocationOutcome,
) -> (
    &lang_build::ReturnedCompleteType,
    &lang_build::StructConstructionMaterial,
) {
    let lang_build::InvocationResult::SemanticResult {
        value: lang_build::ProjectedInvocationOutcome::SingleMember(result),
        ..
    } = outcome
    else {
        panic!("direct struct invocation returns one complete tau value");
    };
    let lang_build::ReturnedSemanticEntity::CompleteType(returned) = &result.returned else {
        panic!("struct result must not expose private meta construction material as its value");
    };
    let material = returned
        .construction_material
        .as_ref()
        .expect("the namespace graph installer retains replayable struct material");
    (returned, material)
}

/// Declaration-path collision: meta evaluation is strictly left-to-right,
/// so when the second `struct` generation collides, the first generation's
/// binding symbol is already known and the hard error points at it.
#[test]
fn second_struct_generation_at_the_same_level_points_at_the_existing_binding() {
    let error = build_fixture_error("ambient_struct_collision", "app");
    assert!(
        error
            .diagnostics
            .iter()
            .any(|diagnostic| diagnostic.message.contains("ambient struct collision")),
        "second generation of the same navigation shape at one level is a hard error: {error:#?}"
    );
    assert!(
        error.diagnostics.iter().any(|diagnostic| {
            diagnostic.message.contains("bound to symbol `A`")
                && diagnostic.message.contains("use the existing `A`")
        }),
        "the collision guidance points at the first generation's whole-symbol binding: {error:#?}"
    );
}

/// World-level collision without a recorded binder: the second direct
/// invocation of the same normalized shape fails with the collision hard
/// error even when the first result was never bound to a symbol.
#[test]
fn second_direct_struct_invocation_collides_in_the_same_world() {
    let mut world =
        CompilationWorld::from_manifest(&BuildManifest::new("app", vec!["app".to_string()]))
            .expect("core semantic world builds");
    let first = invoke_struct(
        &mut world,
        "let T: type = (uint8 a) struct;",
        "ambient collision: first generation",
    )
    .expect("first generation attaches to the ambient declaration environment");
    assert!(matches!(
        first,
        lang_build::InvocationResult::SemanticResult {
            value: lang_build::ProjectedInvocationOutcome::SingleMember(_),
            ..
        }
    ));

    let second = invoke_struct(
        &mut world,
        "let T: type = (uint8 a) struct;",
        "ambient collision: second generation",
    );
    let Err(OrdinaryInvocationFailure::SelectedCoreBody { diagnostic, .. }) = second else {
        panic!("second generation of the same shape at the same level is a hard error");
    };
    assert!(
        diagnostic.message.contains("ambient struct collision"),
        "collision message names the rule: {}",
        diagnostic.message
    );
    assert!(
        diagnostic
            .message
            .contains("use its existing binding to continue the type computation"),
        "without a recorded binder the guidance still points at the existing binding: {}",
        diagnostic.message
    );
}

/// A different normalized body (here: a different field binder name) is a
/// different navigation shape and does not collide.
#[test]
fn different_normalized_body_does_not_collide_at_the_same_level() {
    let mut world =
        CompilationWorld::from_manifest(&BuildManifest::new("app", vec!["app".to_string()]))
            .expect("core semantic world builds");
    invoke_struct(
        &mut world,
        "let T: type = (uint8 a) struct;",
        "ambient collision: shape a",
    )
    .expect("first shape generates");
    invoke_struct(
        &mut world,
        "let U: type = (uint8 b) struct;",
        "ambient collision: shape b",
    )
    .expect("a distinct normalized body is a distinct ambient generation");
}

fn canonical_struct_pattern(spelling: &str) -> CanonicalPatternValue {
    let mut world =
        CompilationWorld::from_manifest(&BuildManifest::new("app", vec!["app".to_string()]))
            .expect("core semantic world builds");
    let outcome =
        invoke_struct(&mut world, spelling, "Pattern layer order").expect("struct invocation");
    returned_struct_material(&outcome)
        .1
        .canonical_pattern_value()
}

#[test]
fn naked_struct_product_is_positional_even_when_every_element_is_named() {
    let ab = canonical_struct_pattern("let T: type = (uint8 a, uint8 b) |> struct;");
    let ba = canonical_struct_pattern("let T: type = (uint8 b, uint8 a) |> struct;");
    assert_ne!(
        ab, ba,
        "`(a, b) != (b, a)`: a naked Product remains positional"
    );
    assert!(matches!(ab, CanonicalPatternValue::OrderedLayer(_)));
}

#[test]
fn named_struct_pattern_body_is_unordered_when_every_child_is_named() {
    let ab = canonical_struct_pattern("let T: type = ((uint8 a, uint8 b) c) |> struct;");
    let ba = canonical_struct_pattern("let T: type = ((uint8 b, uint8 a) c) |> struct;");
    assert_eq!(
        ab, ba,
        "`(a, b)c == (b, a)c`: the named Pattern wrapper gives its fully named \
         body navigation-keyed identity"
    );
    assert!(matches!(
        ab,
        CanonicalPatternValue::NamedPattern { body, .. }
            if matches!(body.as_ref(), CanonicalPatternValue::UnorderedLayer(_))
    ));
}

#[test]
fn struct_accepts_a_named_empty_pattern_and_keeps_its_root_identity() {
    let mut world =
        CompilationWorld::from_manifest(&BuildManifest::new("app", vec!["app".to_string()]))
            .expect("core semantic world builds");
    let outcome = invoke_struct(
        &mut world,
        "let t: type = (() t) |> struct;",
        "named empty struct Pattern",
    )
    .expect("a named empty Pattern is a valid struct result");
    let (_returned, generated) = returned_struct_material(&outcome);
    assert!(generated.fields.is_empty());
    assert_eq!(
        generated.canonical_pattern_value(),
        lang_build::CanonicalPatternBuilder::named_root(
            lang_build::CanonicalFullNavigation::from_component("t")
        )
        .finish(),
        "the empty child map does not erase the top Pattern name"
    );
}

#[test]
fn struct_treats_bare_sum_names_as_pure_patterns_not_fields() {
    let mut world =
        CompilationWorld::from_manifest(&BuildManifest::new("app", vec!["app".to_string()]))
            .expect("core semantic world builds");
    let outcome = invoke_struct(
        &mut world,
        "let boolish: type = ((if | else) boolish) |> struct;",
        "pure no-value sum Pattern",
    )
    .expect("a sum of pure Pattern names is valid struct input");
    let (_returned, generated) = returned_struct_material(&outcome);
    assert!(
        generated.fields.is_empty(),
        "pure Pattern names do not become value-bearing fields"
    );
    let labels = generated
        .sum_struct_pattern_material
        .as_ref()
        .expect("the decoded pure sum remains an exposed sum Pattern")
        .alternatives
        .iter()
        .map(|alternative| alternative.label.as_str())
        .collect::<Vec<_>>();
    assert_eq!(labels, ["if", "else"]);
    assert_eq!(
        generated.canonical_pattern_value(),
        CanonicalPatternValue::NamedPattern {
            navigation: CanonicalFullNavigation::from_component("boolish"),
            body: Box::new(CanonicalPatternValue::Sum(vec![
                CanonicalPatternValue::NamedPattern {
                    navigation: CanonicalFullNavigation::new(["if", "boolish"]),
                    body: Box::new(CanonicalPatternValue::UnorderedLayer(Default::default())),
                },
                CanonicalPatternValue::NamedPattern {
                    navigation: CanonicalFullNavigation::new(["else", "boolish"]),
                    body: Box::new(CanonicalPatternValue::UnorderedLayer(Default::default())),
                },
            ])),
        },
        "zero-value alternatives remain real Pattern structure in the canonical value"
    );
}

#[test]
fn one_shot_inner_field_and_later_explicit_navigation_have_one_pattern_value() {
    let mut world =
        CompilationWorld::from_manifest(&BuildManifest::new("app", vec!["app".to_string()]))
            .expect("core semantic world builds");
    // The executable core slice currently exposes `uint8` as its scalar
    // fixture; the navigation rule is independent of the resident value.
    let resident_type = world
        .resolve_type_value("uint8")
        .expect("core uint8 type resolves semantically");
    let outcome = invoke_struct(
        &mut world,
        "let t: type = ((uint8 inner) t) |> struct;",
        "one-shot inherited inner navigation",
    )
    .expect("the one-shot named Pattern is a valid struct result");
    let one_shot = returned_struct_material(&outcome)
        .1
        .canonical_pattern_value();
    // The one-shot struct crossed a world-connected invocation boundary, so
    // its resident leaf is an OBSERVED `Addr(Norm_type)`; interning is
    // content-idempotent, so replaying the observation yields that address.
    let later_addr = world
        .canonical_type_core_observation_address(resident_type, None)
        .expect("uint8 type observation normalizes");
    let resident_observation = CanonicalTypeObservation::Observed(later_addr);
    let mut later_injection =
        CanonicalPatternBuilder::named_root(CanonicalFullNavigation::from_component("t"));
    later_injection
        .contribute_pattern_value(
            PatternNavigationInput::Explicit(CanonicalFullNavigation::new(["inner", "t"])),
            CanonicalPatternValue::Atom(CanonicalPatternAtom::Type(resident_observation)),
        )
        .expect("the explicit complete navigation is unique");

    assert_eq!(
        one_shot,
        later_injection.finish(),
        "inherited `inner` inside top Pattern `t` and later explicit `inner::t` \
         normalize to one complete-navigation map"
    );
}

fn invoke_struct_under_owner(
    world: &mut CompilationWorld,
    owner: SemanticOwnerId,
    spelling: &str,
    provenance: &str,
) -> Result<InvocationOutcome, OrdinaryInvocationFailure> {
    let initializer = initializer_from_source(spelling);
    let call_site = extract_single_call_site(&initializer).expect("normalized struct call");
    world.invoke_ordinary_call(
        world.package_root_node(),
        &call_site,
        OrdinaryInvocationContext::open_static(&[PolicyMode::Const])
            .with_ambient_construction_owner(owner),
        Provenance::new(provenance),
    )
}

/// The parent-linked Self scope owner of a source callable: the owner that
/// its function-object pattern was allocated under.
fn callable_self_owner(world: &CompilationWorld, name: &str) -> SemanticOwnerId {
    let symbol = world
        .semantic_world()
        .symbol_in_namespace(world.package_root_node(), name)
        .expect("fixture callable symbol");
    let function_value = symbol.sibling_vals[0];
    let object = world
        .semantic_world()
        .value(function_value)
        .expect("function object value");
    assert!(
        matches!(object.payload, SemanticValuePayload::FunctionObject { .. }),
        "callable sibling is a function object"
    );
    world
        .semantic_world()
        .pattern_owner(object.pattern)
        .expect("function object pattern owner")
        .owner
}

fn generated_root(
    world: &CompilationWorld,
    outcome: &InvocationOutcome,
) -> (PatternValueId, TypeValueId) {
    let (returned, _material) = returned_struct_material(outcome);
    let pattern = returned.pattern;
    let type_value = world
        .semantic_world()
        .type_for_pattern(pattern)
        .expect("generated type member pattern pairs with a TypeValue");
    (pattern, type_value)
}

/// B8 — the ambient root prefix is the declaration environment's
/// Self scope chain, not the namespace node: two ordinary functions in one
/// namespace supply distinct Self owners, so the same normalized `struct`
/// shape generates two distinct roots, each rooted under its supplier.
#[test]
fn different_function_self_owners_do_not_share_an_ambient_struct_root() {
    let mut world = build_single_fixture_world("meta_type_roots", "app");
    let owner_f = callable_self_owner(&world, "f");
    let owner_g = callable_self_owner(&world, "g");
    assert_ne!(
        owner_f, owner_g,
        "two callables in one namespace carry distinct Self scope owners"
    );

    let under_f = invoke_struct_under_owner(
        &mut world,
        owner_f,
        "let T: type = (uint8 a) struct;",
        "self chain: struct under f",
    )
    .expect("the shape generates under f's Self scope");
    let under_g = invoke_struct_under_owner(
        &mut world,
        owner_g,
        "let T: type = (uint8 a) struct;",
        "self chain: struct under g",
    )
    .expect("the same shape under a different Self scope is not a collision");

    let (pattern_f, type_f) = generated_root(&world, &under_f);
    let (pattern_g, type_g) = generated_root(&world, &under_g);
    assert_ne!(
        type_f, type_g,
        "same namespace, different function Self -> different ambient roots"
    );
    assert_ne!(pattern_f, pattern_g);

    // Each generated root is owned by exactly the supplied Self owner.
    for (pattern, owner) in [(pattern_f, owner_f), (pattern_g, owner_g)] {
        let root_owner = world
            .semantic_world()
            .pattern_owner(pattern)
            .expect("generated root pattern owner")
            .owner;
        assert_eq!(
            root_owner, owner,
            "the ambient root attaches under the supplied declaration-environment owner"
        );
    }
}

/// Replaying the same normalized shape under one Self owner stays a hard
/// error.
#[test]
fn replaying_the_same_shape_under_one_self_owner_stays_a_hard_error() {
    let mut world = build_single_fixture_world("meta_type_roots", "app");
    let owner_f = callable_self_owner(&world, "f");

    invoke_struct_under_owner(
        &mut world,
        owner_f,
        "let T: type = (uint8 a) struct;",
        "self chain replay: first",
    )
    .expect("first generation under f's Self scope");
    let replay = invoke_struct_under_owner(
        &mut world,
        owner_f,
        "let T: type = (uint8 a) struct;",
        "self chain replay: second",
    );
    let Err(OrdinaryInvocationFailure::SelectedCoreBody { diagnostic, .. }) = replay else {
        panic!("replaying the same shape at one Self level is a hard error");
    };
    assert!(
        diagnostic.message.contains("ambient struct collision"),
        "collision message names the rule: {}",
        diagnostic.message
    );
}
